---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: shodobot
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: 20c0686f-7086-4844-8604-fc14c606ab2a
      accessKey:
        secretRef:
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-secret
          key: secret-access-key