apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leann-documents
  namespace: shodobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: lssd
